
name: Python application Peak Conditition

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  adequacao_pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle        
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run teste with pycodestyle
      run: |
        pycodestyle --max-line-length=120 ingestion_data/

  adequacao_pydocstyle:
    runs-on: ubuntu-latest
    needs: adequacao_pycodestyle
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle        
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      
    - name: Run teste with pydocstyle
      run: |
        pydocstyle ingestion_data/    

  Testes:
    runs-on: ubuntu-latest
    needs: adequacao_pydocstyle
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas
        pip install awswrangler       
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
    - name: Testes unitários ingestion
      run: |
        python -m unittest discover test_ci/test_ingestion -v

   
